version: '3.8'
services:
  # Zookeeper service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka broker service
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # PostgreSQL database : user-service
  postgres1:
    image: postgres:13
    container_name: postgres1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: users
    ports:
      - "5431:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data

  # PostgreSQL database : product-service
  postgres2:
    image: postgres:13
    container_name: postgres2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data

  # PostgreSQL database : inventory-service
  postgres3:
    image: postgres:13
    container_name: postgres3
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: inventory
    ports:
      - "5433:5432"
    volumes:
      - postgres3_data:/var/lib/postgresql/data

  # PostgreSQL database : order-service
  postgres4:
    image: postgres:13
    container_name: postgres4
    environment:
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: password4
      POSTGRES_DB: orders
    ports:
      - "5434:5432"
    volumes:
      - postgres4_data:/var/lib/postgresql/data

  # PostgreSQL database : payment-service
  postgres5:
    image: postgres:13
    container_name: postgres5
    environment:
      POSTGRES_USER: user5
      POSTGRES_PASSWORD: password5
      POSTGRES_DB: payments
    ports:
      - "5435:5432"
    volumes:
      - postgres5_data:/var/lib/postgresql/data

  # PostgreSQL database : notification-service
  postgres6:
    image: postgres:13
    container_name: postgres6
    environment:
      POSTGRES_USER: user6
      POSTGRES_PASSWORD: password6
      POSTGRES_DB: notifications
    ports:
      - "5436:5432"
    volumes:
      - postgres6_data:/var/lib/postgresql/data

  # PostgreSQL database : security-service
  postgres7:
    image: postgres:13
    container_name: postgres7
    environment:
      POSTGRES_USER: user7
      POSTGRES_PASSWORD: password7
      POSTGRES_DB: security
    ports:
      - "5437:5432"
    volumes:
      - postgres7_data:/var/lib/postgresql/data

volumes:
  postgres1_data:
  postgres2_data:
  postgres3_data:
  postgres4_data:
  postgres5_data:
  postgres6_data:
  postgres7_data: